### ISSUE TITLE
Shouldn't getLocations use Location[] instead of Object[] in Typescript definitions? 

### ISSUE THREAD

**Issue by PauliusLiekis** [transistorsoft/react-native-background-geolocation#1212]
## Your Environment
* Plugin version: 3.9.3

## Description

Current definition of `getLocations`:

`static getLocations(success?:(locations:Array<Object>) => void, failure?:Function): Promise<Array<Object>>;`

Shouldn't it be:

`static getLocations(success?:(locations: Location[]) => void, failure?:Function): Promise<Location[]>;` ?

Even API docs say:

> Retrieve a List of [[Location]] currently stored in the SDK's SQLite database.

If that's not the case could you elaborate on the type of the `Object`?

**Comment by christocracy** [comment]
In a perfect world, yes.  However, because [`Config.locationTemplate`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#locationtemplate) allows one to customize the schema of the recorded location, there's no guarantee the results conform to the `Location` definition.

**Comment by christocracy** [comment]
The plugin inserts a JSON representation of each recorded location into its SQLite database at the instant the location is recorded.  As noted above, the JSON schema is influenced by `Config.locationTemplate`.

The plugin's locations table in SQLite looks like this:

```
| id | timestamp | uuid | json |
```

**Comment by PauliusLiekis** [comment]
Ah, this makes sense. Thank you!
