### ISSUE TITLE
please help how to fix this 

### ISSUE THREAD

**Issue by pasiiii** [transistorsoft/react-native-background-geolocation#1237]
Could not get unknown property 'enableSeparateBuildPerCPUArchitecture' for object of type com.android.build.gradle.internal.dsl.AbiSplitOptions.

**Comment by christocracy** [comment]
No idea, never heard of it.  You're providing almost no information.

**Comment by christocracy** [comment]
And you **ignored the issue template**.  

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by pasiiii** [comment]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User\AndroidStudioProjects\projectname\android\app\build.gradle' line: 60

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'enableSeparateBuildPerCPUArchitecture' for object of type com.android.build.gradle.internal.dsl.AbiSplitOptions.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by christocracy** [comment]
**Edit your issue** and provide **ALL** the information requested in the issue template.

**Comment by pasiiii** [comment]
![error](https://user-images.githubusercontent.com/78813991/107401862-4d524300-6b29-11eb-8ac8-36ab6dc3e4f4.JPG)

**Comment by christocracy** [comment]
**Edit your issue** and provide **ALL** the information requested in the issue template.

This issue is closed until you do so.
