### ISSUE TITLE
Method to get motion authorization status

### ISSUE THREAD

**Issue by jamesloper** [transistorsoft/react-native-background-geolocation#1333]
Hey, guys. I'd like to know if there's any way to retrieve the device's present iOS authorization status for the motion permission. I'm trying to accomplish a UI such as this:

![image](https://user-images.githubusercontent.com/8919598/124805043-f9f1ee80-df28-11eb-8b50-7aa607aa452b.png)

I believe this is the native permission in question...
https://developer.apple.com/documentation/coremotion/cmmotionactivitymanager/2913744-authorizationstatus

**Comment by mikehardy** [comment]
https://github.com/zoontek/react-native-permissions

**Comment by jamesloper** [comment]
Any way to do it with only Transistorsoft?

**Comment by jamesloper** [comment]
Not stale, clearly the requisite native code is already in the package somewhere...perhaps an undocumented RN api?

**Comment by jamesloper** [comment]
Holding out hope 🙃

**Comment by superyarik** [comment]
hey, also interesting how to check status of Physical activity in general?

in Android i can check it 
```
PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.ACTIVITY_RECOGNITION).then((permissionStatus) => {
    console.log('RES1');
    console.log(permissionStatus);
});
```

but how we can check it in ios?

asking because we are managing all permissions (background, foreground, and trying to Physical activity) in app flow before trying to start() in react-native-background-geolocation
