### ISSUE TITLE
Why not display  'always allow' option in location permission popup?

### ISSUE THREAD

**Issue by abhishekSutariya1** [transistorsoft/react-native-background-geolocation#1338]
## Your Environment
* Plugin version: 4.0.2
* Platform: iOS or Android: Both
* OS version: 
* Device manufacturer / model: oneplus 8T & Iphone 7 plus
* React Native version (`react-native -v`): 0.63.4

## Expected Behavior
On Android & ios, I have asked permission for the location of always but that does not display **Always Allow**. Tell me Is anything in plug in to display this.

Please Check Screen Shot for more information.
![unnamed](https://user-images.githubusercontent.com/82496722/125153018-95c06c00-e16e-11eb-977d-872e42559da1.png)

## Context
ask location permission for always allow.

**Comment by christocracy** [comment]
You need to ask *Apple* this question -- this dialog is managed by the operating system.

**Comment by mikehardy** [comment]
You might like this explanation (this plugin can manage the permissions requests internally but react-native-permissions just serves as a good explanation here since they both work under the same operating system constraints) https://github.com/zoontek/react-native-permissions#about-ios-location_always-permission
