### ISSUE TITLE
Support question about configuration

### ISSUE THREAD

**Issue by kmcb777** [transistorsoft/react-native-background-geolocation#1510]
## Your Environment
* Plugin version: 4.7.1
* Platform: both
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`): 0.67.4
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
    desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
    distanceFilter: 5,
    stationaryRadius: 1,
    stopOnTerminate: true,
    reset: false,
    foregroundService: true,
    showsBackgroundLocationIndicator: true,
```

Hi,

First, thanks for making this plugin.
This is more a support question than a bug (we don't have slack support because only on Starter Plan).
We're close to having the geolocation fully working on our app, but we have two remaining questions about the setup of the plugin :

- Concerning the `ready` method, the doc says we mustn't use any other `BackgroundGeolocation` method before `ready` has finished, but adding the `onLocation` listener seems to work only if used before `ready` (and it's like this in the example app).
Could you confirm that we must use it before ?
Also, according to the doc we mustn't call `ready` twice. Is there a way to know if it's already been called ? I have trouble knowing if i have to re-launch it after the app has been killed. It seems it doesn't work without doing it, but on the other hand the geolocation sometimes seems to stay active after the app is killed (there is still the icon in the phone status bar) and then it doesn't start again when i re-open the app, so there may be a problem with our setup.

- On ios when the app is in background, the plugin sometimes seems to pause until the app is opened again, and no more locations are received, is it a known issue on ios ? Is there something we can do to prevent this ?

**Comment by christocracy** [comment]
>reset: false,

Why are you using this?  99% of use-cases don't need this.  If you don't know *exactly* what `reset: false` does, don't use it.  **Delete** that line from your config.

>Concerning the ready method, the doc says we mustn't use any other BackgroundGeolocation method before ready has finished,

Any method which requests a location (eg: `.getCurrentPosition()`, `.start()`).  You are *encouraged* to add event-listeners before `.ready()`.  Adding an event-listener (eg: `onLocation`) does nothing more than add a `callback` to an `array`.

`.ready()` is a signal to the plugin that your app is launched and ready to receive events.  If you don't listen to events before `.ready()`, you could miss several initial events.

> Is there a way to know if it's already been called ?

It's not the end of the world if you do.  The plugin is just going to relay your call to `.ready()` to `.setConfig`.  Calling `.ready()` does not imply "start tracking location".  Only calling `.start()` begins location-tracking.

```javascript
initMyApp() async {
  BackgroundGeolocation.onLocation((location) => {
    console.log('[onLocation] ', location);
  }

  const state = await BackgroundGeolocation.ready(myConfig);
  console.log('- State: ', state.enabled);
}

startTracking() async {
  BackgroundGeolocation.start();
}

stopTracking() async {
  BackgroundGeolocation.stop();
}
```

>On ios when the app is in background, the plugin sometimes seems to pause

If the plugin is in the *stationary* state, your app **IS** paused.  Only when the plugin is in the *moving* state (where location-services are ON and the location icon in statusbar is activated, will your app continue to stay awake in the background.

See Wiki [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

>is it a known issue on ios ? Is there something we can do to prevent this ?

This is not an "issue".  This is the normal behaviour of an iOS app which goes to the background without location-services turned on.

**Comment by christocracy** [comment]
>If we decide to use the preventSuspend option, do we need to implement the 'onHeartbeat' or will the 'onLocation' handler keep triggering as usual ?

Adding event listeners does not affect the behaviour of the plugin.  Adding an event-listener does nothing more than push a `callback` function onto an array.

You do not understand `preventSuspend`.  Have you read the API docs about it?  `onHeartbeat` fires *only* when the device is stationary, when **location-services are OFF**.  There are no locations being recorded when `onHeartbeat` event is firing.  iOS-only `preventSuspend` requires a `heartbeatInterval > 0`.

When the device is in the *moving* state, where location-services are ON and the plugin recording locations and broadcasting them to your `onLocation` event-handler, there is no `onHeartbeat` events being fired.  Heartbeat **stops** when the device is detected to be moving and the plugin recording locations.

It is recommended to **avoid** using the iOS-only `preventSuspend` since it will consume *a lot* more battery power.

Read the wiki [Philosophy of Operation](https://github.com/transistorsoft/react-native-background-geolocation/wiki/Philosophy-of-Operation)

>Also, i saw that my colleagues who used this plugin in a previous projet did this :
>Will it keep the location-services awake until we call stop() ?

It will keep location-services ON until the `Config.stopTimeout` expires.  Read the API docs for `Config.stopTimeout`, `.changePace`.

**Comment by kmcb777** [comment]
Ok thanks for the answers, i wanted to double-check since i'm not familiar with geolocation, and i indeed misunderstood what "location-services are OFF" means.
