### ISSUE TITLE
Question > about google play services

### ISSUE THREAD

**Issue by TacticCoder** [transistorsoft/react-native-background-geolocation#1550]
If we have a device that didn't have the google play services installed, what will happen? there is a fallback?

**Comment by christocracy** [comment]
This plugin **requires** Google play services.

there is no fallback.

**Comment by mikehardy** [comment]
Well, there *is* the potential fallback of using a different module - this one is the community one and does a fallback if Play Services is not available (perhaps that is possible @christocracy ?) https://github.com/michalchudziak/react-native-geolocation

The big big big difference there is that the fallback would be missing the motion API though, meaning that all the work this plugin does to carefully manage the user battery in stationary conditions would be inaccessible.

That *may* be a tradeoff worth making for lots of cases, possibly even the disaster assistance ones the plugin was originally developed for. Worth a thought

It is also possible to use the HMS motion-api-copy (https://medium.com/huawei-developers/activity-identification-service-hms-location-kit-68859bf46456) to perhaps achieve the same thing on devices that are HMS instead of GMS, meaning the library could/would cover another big slice of the market as I *think* most of the non-GMS devices are probably HMS. I had a look for an analog for Xiaomi and couldn't find one, maybe they bundle HMS, I dunno

**Comment by TacticCoder** [comment]
@christocracy  I have to agree with @mikehardy, because of the lack of partial support, I will have to choose between two dependencies at runtime since we have customers that need the app but can't use the google play services.

**Comment by christocracy** [comment]
My first Huawei HMS phone (*Nova 9 SE @ EMUI 12.0.1*) arrived today and the plugin's new HMS proxy worked on first boot of the demo app.
