### ISSUE TITLE
Question about filtering/accuracy

### ISSUE THREAD

**Issue by SharfMohiuddin** [transistorsoft/react-native-background-geolocation#1565]
Hi! We have a question about the dataset that is generated by the plugin . The plugin successfully determines the event type however, when switching from one event to another it generates points that are not valid. See the S.S, we understand that it required some distance/time for it to correct itself. Unfortunately,  the plugin gives no info as to if the point that is being captured a valid one or not. See accuracy in S.S. The question is how to predict certain events like these. If we filtered the dataset on basis of accuracy, speed and distance we lose too much data points which results in the dataset being too abnormal.
We know that you test the plugin with different devices and say that everthing is fine on your end. Can you please share your filtering method in order to reduce the noise in your dataset.

Second question, sometimes the plugin is super accurate (eventType: Driving) and sometimes it is not even though the path is the same and clear skies are present. Could you please explain why the accuracy always changes. Is it because of the satellite position? But even in that case how do navigator e.g. Google maps, Apple maps correctly determine where you are located at
Using the plugin if we walk around tall buildings the GPS signals become weak as a result of that the data points are not 100% accurate but again all the navigators correctly determine where the device is located at. Is there something on OS level that they are taking advantage of that the plugin does not. 

Looking forward for your clarifications. 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/111132563/196121682-5e7e66de-5ded-4015-85c0-64e629f99f81.png)

**Comment by christocracy** [comment]
>when switching from one event to another it generates points that are not valid

Are you aware of the `Location` property `Location.sample`?

You've ignored the issue template, which asked you to provide the `Config` you're providing the plugin so I have no idea if you've configured `Config.url` (enabling the plugin's built-in HTTP service) or whether you're uploading location with your own application code.

>Can you please share your filtering method in order to reduce the noise in your dataset.

I do not filter data.  I *want* to see *all* data, even when poor.  You're expected to filter your own data based upon `accuracy`.

>Second question, sometimes the plugin is super accurate (eventType: Driving) and sometimes it is not even though the path is the same and clear skies are present. Could you please explain why the accuracy always changes

The plugin does not *manufacture* location data.  It merely subscribes to the native ios and Android location aps, the same apis used by any pure native app (eg: Google Maps, Apple Maps).  The plugin is only the messenger, delivering locations to you exactly as provided by the native location apis.  The plugin does not have any way of influencing the accuracy of data (other than `Config.desiredAccuracy`.  You've *probably* provided `DESIRED_ACCURACY_HIGH` or `DESIRED_ACCURACY_NAVIGATION`...I don't know since you *ignored the issue template*.

**Comment by christocracy** [comment]
> should we use other to improve the tracking result.

As I said:  “*The plugin **does not have any way of influencing the accuracy** of data*”
