### ISSUE TITLE
Error on getGeofences()

### ISSUE THREAD

**Issue by robmoorman** [transistorsoft/react-native-background-geolocation#158]
With version 1.5.2 I get an error while fetching my registered geofences.
There is one geofence added to the instance.

Error:
```
ExceptionsManager.js:82 Exception '-[__NSDictionaryM identifier]: unrecognized selector sent to instance 0x796d1df0' was thrown while invoking getGeofences on target RNBackgroundGeolocation with params (
    56,
    57
)
```

JavaScript (script lives within componentWillReceiveProps lifecycle method):
```javascript
fence.getGeofences((geoFences) => {
  geoFences.forEach((geoFence) => {
    ...
  })
})
```

**Comment by christocracy** [comment]
I looks like you're sending an `Array [56, 57]` as the first parameter of the the method `#getGeofences`, which requires a `Function`.

**Comment by robmoorman** [comment]
He @christocracy the `(geoFences) => {}` notation (ES6) is actually an anonymous function.

**Comment by christocracy** [comment]
Also, you should generally not require the `#getGeofences` method anymore since the geofencing system was refactored.

The plugin can now monitor [Infinite geofences](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/geofencing.md) -- it is no longer limited to 20 for iOS.

Instead, you should listen to the new `geofenceschange` event -- the plugin will tell you what geofences it's monitoring within the configurable `geofenceProximityRadius`.

See [here](http://www.transistorsoft.com/shop/products/assets/images/background-geolocation-infinite-geofencing.gif) for an animation of the new geofencing behaviour.

**Comment by robmoorman** [comment]
Will give the `geofenceschange` event a try!

**Comment by christocracy** [comment]
However, I see there is a bug in `getGeofences`.  I wasn't migrated to the data-format.  I can fix this right away.  Still, you should migrate your code to not use `getGeofences`.  Since the plugin can now monitor *thousands* of geofences, `getGeofences` will return those thousands of records.

`geofenceschange` event will provide `#on` and `#off` arrays, letting you know which geofences are currently in proximity (`#on`) and those which just moved *out of proximity* (`#off`).

**Comment by christocracy** [comment]
Fixed in master.

**Comment by robmoorman** [comment]
Thanks!
