### ISSUE TITLE
Execution failed for task ':app:installDebug'.

### ISSUE THREAD

**Issue by RuFang-21** [transistorsoft/react-native-background-geolocation#1640]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to install on any devices.

**Comment by christocracy** [comment]
The issue template is **not** optional, it's *required*.



*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
