### ISSUE TITLE
Cocoalumberjack

### ISSUE THREAD

**Issue by aksonov** [transistorsoft/react-native-background-geolocation#168]
1.4.5 version doesn't work without rnpm link of Cocoalumberjack, but this way i can't use this library with other components that contains Cocoalumberjack (like react-native-xmpp). Even if i would remove that third-party library from XMPP iOS framework, app will fail because XMPP depends from other version...

P.S. 1.4.3 works fine

**Comment by christocracy** [comment]
There will be some growing pains.

In this case, you should talk to the people at XMPP, who've copied CocoaLumberjack right into their repo.

**Comment by christocracy** [comment]
At least I ripped the `CocoaLumberjack` static lib out my code and have you import the framework from the source (best method is with Cocoapods).  [`XMPPFramework`](https://github.com/robbiehanson/XMPPFramework/tree/db543e1b484687768024ce3e78e9f287fbee4aa6/Vendor/CocoaLumberjack) copies the source of CocoaLumberjack directly into their product, and hasn't in **3 years!**.  The problem is *certainly* over there, not here.
![](https://www.dropbox.com/s/wple2gx4eas51jf/Screenshot%202016-11-13%2023.26.17.png?dl=1)
