### ISSUE TITLE
No API calls are been triggered for locations sync on my api server [Android/IOS] Detailed Logs have been attached

### ISSUE THREAD

**Issue by karankapur999** [transistorsoft/react-native-background-geolocation#1706]
Hi 

PFA the debug logs and help me find out why are the locations not been synced with my API server ?
[background-geolocation.log](https://github.com/transistorsoft/react-native-background-geolocation/files/11711477/background-geolocation.log)

**Comment by karankapur999** [comment]
@christocracy 

Please do help on this as it is causing lot of issues on our Production

**Comment by christocracy** [comment]
Ignored issue template:




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by karankapur999** [comment]
>
