### ISSUE TITLE
(retired) SHA-1 being used by Huawei packages

### ISSUE THREAD

**Issue by mwmcode** [transistorsoft/react-native-background-geolocation#1756]
Hi Chris,
> I know this is not an "issue" but I didn't know where to post it since there is no Discussion tab on this repo

A recent security review of our app has resulted in the following warnings:
```md
## SHA-1 is being used

com/huawei/agconnect/config/impl/i.java
com/huawei/hms/hatool/e.java

**Security Risk**: The SHA-1 hash has been deemed as insecure and has been retired. 
The hash has been previously associated with multiple vulnerabilities 

Additional information: 

- https://www.nist.gov/news-events/news/2022/12/nist-retires-sha-1-cryptographic-algorithm 
- https://www.computerworld.com/article/3173616/the-sha1-hash-function-is-now-completely-unsafe.html
```

https://github.com/transistorsoft/react-native-background-geolocation/blob/master/android/build.gradle

- is this package used on android builds? 
- if not, can we disable it before we build for android?
- assuming upstream has dropped SHA-1, is it possible to pull an updated version of huawei packages? _I couldn't find source code for huawei packages, not sure where to look for them actually_

**Comment by christocracy** [comment]
> is this package used on android builds?

no, but the symbols must exist since the plug-in uses a proxy layer to route calls to Google GMS or Huawei GMS as appropriate.

> if not, can we disable it before we build for android?

No.

The plug-in now supports installation on Huawei devices with Huawei Mobile Services (HMS).  These devices do not have Google Play Services installed due to trade embargo by USA.

If you’re not using Huawei devices with HMS, then anything related to Huawei is meaningless to you and not used.

you can safely ignore that warning.  It does not affect you at all.
