### ISSUE TITLE
custom layout with expo plugin?

### ISSUE THREAD

**Issue by pixelkoduje** [transistorsoft/react-native-background-geolocation#1834]
How to add custom xml layout with expo plugin?

**Comment by christocracy** [comment]
I don’t know.  I guess you’d have to create a custom Expo plug-in to inject your desired xml file into your app.

**Comment by pixelkoduje** [comment]
You have an idea? As in. inject any file? Is this possible in the expo custom plugin?

**Comment by christocracy** [comment]
Like k said:  “I don’t know”

**Comment by pixelkoduje** [comment]
And how do I inject the file, to a place that does not exist XD Android folder does not exist, so through the "fs" library I am not able to drop the file, to such a place.

**Comment by christocracy** [comment]
**I don’t know**.  I have little experience with Expo.

**Comment by superyarik** [comment]
@pixelkoduje look to another expo plugins.
f.e. [here](https://stackoverflow.com/questions/55372642/how-to-add-network-security-config-xml-to-manifest-in-expo-app-without-ejecting) xml file coping from project to android folder

**Comment by Kriznar** [comment]
This is the solution.
Edit your metro.config.js in such a way:
let config = getDefaultConfig(__dirname);
config.resolver.assetExts.push('xml');
module.exports = config;

This includes xml files in app/src/main/res/layout folder. Then put your template file in this folder and it should work.

@christocracy Maybe this could be added to the documentation so that Expo users can use this.
