### ISSUE TITLE
Cannot read property 'ready' of null

### ISSUE THREAD

**Issue by mumnanikunj** [transistorsoft/react-native-background-geolocation#1836]
Hello
any one help me 
getting me in my current project error
and also  i have anthor error Cannot read property 'ready' of null
but demo project work properly

**Comment by christocracy** [comment]
Ignored issue template.  The issue template is not optional, it’s **required**.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by mumnanikunj** [comment]
why add tag IGNORED ISSUE TEMPLATE @christocracy

**Comment by christocracy** [comment]
Because you ignored the issue template
