### ISSUE TITLE
General Question:  Can this be used with exponent?  TIA

### ISSUE THREAD

**Issue by rrrodzilla** [transistorsoft/react-native-background-geolocation#184]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Steps to Reproduce

1.
2.
3.
4.

**Comment by christocracy** [comment]
If [Exponent](https://docs.getexponent.com/versions/v12.0.0/guides/how-exponent-works.html) uses React Native, it should work.  The plugin can work with pure native apps too.  The React Native-ness is merely a thin facade to a pure native library.

The plugin has adapters for Cordova and NativeScript, as well.  I'm sure it'll work with this Exponent.

**Comment by rrrodzilla** [comment]
Thanks Chris.  Exponent currently only works with pure javascript libraries.  I'll give it a go and report back for your future information.  Thanks again!

**Comment by christocracy** [comment]
Update?

**Comment by christocracy** [comment]
I got the plugin working with Exponent.  It was my first experience with Exponent.

It took me about an hour, including initial Exponent setup.

You will have, of course, have to "detach" your Expo app in order to use the plugin.

Once detached, I basically followed this plugin's [Cocoapod Setup](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-IOS-COCOAPODS.md)

The only hiccup I had was a dependency issue on `CocoaLumberjack` (my plugin uses latest) but `ExpoKit` relies upon `2.7.0`.

I simply edited `.expo-source/ios/ExpoKit.podspec` and modified the dependency to `~> 3.0`.

```
+s.dependency 'CocoaLumberjack', '~> 3.0'
```

After that, I edited my Expo app's `main.js`:

```javascript
import Expo from 'expo';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import BackgroundGeolocation from "react-native-background-geolocation";

class App extends React.Component {
  componentDidMount() {

    BackgroundGeolocation.on('motionchange', (event) => {
      console.log('motionchange', event);
    });
    BackgroundGeolocation.on('location', (location) => {
      console.log('location', location);
    });
    BackgroundGeolocation.on('providerchange', (provider) => {
      console.log('providerchange', provider);
    });
    BackgroundGeolocation.configure({debug: true, logLevel: 5}, (state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start();
      }
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Open up main.js to start working on your app!</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

Expo.registerRootComponent(App);
```

Do a restart in **Expo XDE**, then Run the project.  Simulate location in Simulator with City Drive and the plugin starts talking.

![](https://www.dropbox.com/s/ydn3xzzeonvm95u/Screenshot%202017-03-31%2010.55.58.png?dl=1)
