### ISSUE TITLE
Background geolocation doesn't starts immediately

### ISSUE THREAD

**Issue by Sarveshwins** [transistorsoft/react-native-background-geolocation#1880]
The background geolocation takes a long time to start when I keep the app in the killed state, and it doesn't start when I am walking. However, when I am riding a bike, then coordinates are received after passing some distance

On android its working fine its happening in case of ios

**Comment by christocracy** [comment]
Because, you ignored the issue template, which have no idea what to tell you.  You're not even specifying iOS or Android.

The issue template is not optional.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
