### ISSUE TITLE
BackgroundGeolocation updates once a second with distance filter set to 500

### ISSUE THREAD

**Issue by JustynRoseRocket** [transistorsoft/react-native-background-geolocation#1901]
## Your Environment
* Plugin version:
    react-native-background-fetch: "^4.2.1",
    react-native-background-geolocation: "^4.14.2"
* Platform: iOS
* OS version:iOS 17.0
* Device manufacturer / model: Simulator iPhone 15 pro
* React Native version: react-native: 0.72.5
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
BackgroundGeolocation Config:
{
  disableElasticity: true,
  reset: false,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  allowIdenticalLocations: false,
  locationTemplate:
    '{"lat":<%= latitude %>,"lon":<%= longitude %>,"timestamp":"<%= timestamp %>"}',
  httpRootProperty: '.',
  autoSync: true, // attempt to immediately upload recorded location
  autoSyncThreshold: 1,
  batchSync: false,
  maxDaysToPersist: 14,
  maxRecordsToPersist: 1, 
  desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_NAVIGATION,
  showsBackgroundLocationIndicator: true,
  distanceFilter: 1000,
  elasticityMultiplier: 1,
  stationaryRadius: 50,
  disableElasticity: true,
  reset: false,
  debug: false,
  logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
  allowIdenticalLocations: false,
}

BackgroundFetch Config:
{
  minimumFetchInterval: 50, // fetch every 50 minutes
  forceAlarmManager: true, 
}
```

## Expected Behavior

When simulating a "freeway drive" with the iOS simulator background fetch sends updates every 50min. We also expect location updates are to be reduced  if the driver is moving quickly. 
## Actual Behavior

When simulating a "freeway drive" with the iOS simulator background location sends updates every second. 

## Steps to Reproduce

1.use our config
2.
3.
4.

## Context

Reduce the number of calls when a vehicle is moving quickly. We're also trying to setup location updates on iOS every ~50 min. What is the best way to achieve this behavior on iOS. is there a better way to test on physical devices that the background update/fetch is called correctly?

## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
>  reset: false,

Do you know what this does?  Why are you using it?

**Comment by vhenri** [comment]
Hey @christocracy - jumping in here since @JustynRoseRocket is on vacation. It looks like our team mistakenly had `reset:false` set; thanks for pointing that out! 

However, after changing this back to default, we're still seeing ios send a lot more calls than we'd like. Are there any other settings that you'd recommend our team try out to recuce the number of calls on ios? 

Our infra team is adimant that we only send at most once per 15 min (ideally every 50 min), so I'm considering handling the http requests ourselves from within the location subscriber callback. However I know [in the docs](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/config.html#url) you strongly suggest to let the plugin handle these requests, so I've been hesitant to go that route. 

My other consideration was to enable `batchSync` with a higher `maxBatchSize` for iOS, but I think that would result in a too-low call frequency when users are moving slower or stuck in traffic. 

Any thoughts or suggestions would be greatly appreciated! 🙏🏻

**Comment by christocracy** [comment]
See api docs Config.useSignificantChangesOnly

The iOS location api operates on distance only.   You get to say "I want a location every x minutes".

You're free to implement the background-fetch plugin (already included as a dependency; see its readme) to periodically call .getCurrentPosition.

**Comment by vhenri** [comment]
We do use the background-fetch to get current position 🙂 However, our requirements are to have a location every _x_ minutes (achieved via background-fetch) and every _x-n_ minutes when the user is moving (ideally achieved with this library). 

I don't mind if we end up fetching the location more frequently due to the iOS location api, I'm more concerned about the frequency of the http requests. I'm looking for a "I want to sent a location to my endpoint every x minutes" or "I want to send a location _no more than_ once every x minutes". 

I did also consider the `Config.useSignificantChangesOnly`, but I worry that a user stuck in traffic would not trigger the location frequently enough. 😅 

Thoughts?

**Comment by christocracy** [comment]
> However, our requirements are to have a location every x minutes

Requirements are not always possible.

**Comment by vhenri** [comment]
Actually, to follow up - I'm running the simulator on "freeway drive" with `useSignificantChangesOnly` enabled and I'm still seeing one location / minute on our endpoint. So this param unfortunately is not quite what we're looking for 😕

**Comment by christocracy** [comment]
Freeway drive simulates a device moving at ~100km / hr.

**Comment by vhenri** [comment]
> > However, our requirements are to have a location every x minutes
> 
> Requirements are not always possible.

Hmm, fair! But limiting the calls to our endpoint should be possible. Just hoping to solve this via `react-navive-background-geolocation`.  As I mentioned, this requirement is the most important to the team right now `I want to send a location no more than once every x minutes`.

**Comment by christocracy** [comment]
> autoSync: true, 

You're free to disable autoSync and call .sync() whenever you wish.

**Comment by vhenri** [comment]
> Freeway drive simulates a device moving at ~100km / hr.

Yup! Which is probably why the significantChangesOnly isn't the best option for our use case 😅

**Comment by vhenri** [comment]
> > autoSync: true,
> 
> You're free to disable autoSync and call .sync() whenever you wish.

Hmmm, this is a good point! Since we have `maxRecordsToPersist: 1`, this seems to achieve what I'm looking for (thank you!): 

```
BackgroundGeolocation.onLocation(
    async locationObject => {

      // check the last time we synced the location with server
      const lastSyncTime = await getAsyncStorageValue(
        '@lastSyncedLocationTime',
        { timestamp: 0 },
      );

      // if it's been more than LOCATION_UPDATE_INTERVAL, sync the location
      if (shouldSyncLocation(lastSyncTime.timestamp)) {
        BackgroundGeolocation.sync(async records => {
          LOG.debug('[onLocation] - sync success', records);

          await setAsyncStorageValue('@lastSyncedLocationTime', {
            timestamp: Date.now(),
          });
        })
      } else {
        LOG.debug('[onLocation] - skipping sync. ');
      }
    }
  );
  ```
  
However, I also have a button that can manually send a one-time location value. This isn't restricted by the "no more than x minutes" requirements (yes, a user can theoretically spam this, but that's not a specific concern right now). If i implement the above, this functionality will break if the user has synced in the last x minutes. 
  
 Curious if you have any thoughts or suggestions on how to solve for this additional constraint? I understand that the [`onLocation` subscriber ](https://transistorsoft.github.io/react-native-background-geolocation/classes/backgroundgeolocation.html#onlocation) receives the location from getCurrentPosition / onMotionChange / watch position and I don't think there is any way to pass any additional context about how the location was called to the onLocation, is there?

**Comment by vhenri** [comment]
Oh wait, never mind. I guess I can just call `.sync()` after this button click 😅 

My brain is shutting down this last day before the holidays! Thanks for your help - happy holidays + hope you have a wonderful new year! 😊
