### ISSUE TITLE
Not working on real android devices

### ISSUE THREAD

**Issue by MobileTallent** [transistorsoft/react-native-background-geolocation#1903]
My license key is valid. And the BackgroundGeolocation.onLocation works good on emulator, even if its the release APK. but not working on real android devices.

What's the reason?

**Comment by christocracy** [comment]
The "issue template" is not optional, it's **required**.


*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
