### ISSUE TITLE
I want to print & send to server the location details in each 2 min even when the app is in background

### ISSUE THREAD

**Issue by iasreact1** [transistorsoft/react-native-background-geolocation#1924]
Please help me i copy the code of example but it will just print the location once , i want to print and send to server the location in every 2 min even when the app is in background, please help me i am new to background location ...

**Comment by christocracy** [comment]
Ignored issue template.  The issue template asked you to provide information.

**Comment by christocracy** [comment]
## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
