### ISSUE TITLE
react-native-background-geolocation 4.12.1  application is crash 

### ISSUE THREAD

**Issue by arashadkamran-sdn** [transistorsoft/react-native-background-geolocation#1929]
android buid.gradlew 
       googlePlayServicesLocationVersion = "20.0.1"
      add this

**Comment by christocracy** [comment]
Ignored issue template.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
