### ISSUE TITLE
Heartbeat on closed iOS app

### ISSUE THREAD

**Issue by JAStanton** [transistorsoft/react-native-background-geolocation#197]
When my iOS app is stationary and I request heartbeats and I have preventSuspend on I will get location updates when the app is in the background even if I am not moving. This can happen if I ask for the `location` capability from the app. That's great, but will I still get heartbeats if:

1) the user force closes the app? 
2) Or force closes and restarts the device?
3) Also what if I don't ask for "Motion & Fitness" API, I see you discourage this but will the app still detect becoming still and thus turn on the heartbeats or will heartbeats not work in that situation as well?
4) How does `preventSuspend` work? the [docs](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW1) say `Enabling this mode does not prevent the system from suspending the app,`. While you say `preventSuspend will keep your app running indefinitely in the background`

Additionally for android
1) will I get Heartbeat events if the user force closes the app and is stationary?
2) what about force close and restart the device?
3) is the default android behavior the same as preventSuspend on iOS?

Context:
Building a fleet tracking app. My fleet has 2 configurations, active: where I am aggressive at getting heartbeats every minute, and the driver is expected to trigger geofences. And inactive: I expect to get location updates every 10 minutes or so. 

I use both your iOS and your android builds and I have a license for android.

**Comment by christocracy** [comment]
1.  No.
2. No.  However, before your app terminates, it creates a geofence around the last-known position.  if the device exits this stationary-geofence, regardless if the user terminates the app or reboots the device, your app **will** come alive again.  When your app is alive, `heartbeat` events will fire.
3.  Yes, the plugin will use a **HIGHLY INFERIOR** accelerometer-only mechanism.  The plugin is **highly** optimized to use "Motion & Fitness" permission.  You will consume more battery power if you disable this.
4.  `preventSuspend` will keep your app alive in the background by periodically requesting a location-update which resets the maximum 200s background-time.

**Android**
1. Yes
2. Android `heartbeat` only fires when your `MainActivity` (where your Javascript lives) is running.  If the plugin is running "headless" (eg: due to device reboot or app terminate with `stopOnTerminate: false, startOnBoot: true`), you won't receive `heartbeat` events because your Javascript isn't alive to receive these events.  Only the pure native background-service is running in this case.  You might want to investigate the Android [`forceReload*`](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#param-boolean-forcereloadonmotionchange) config options.
3. There is no analog for `preventSuspend` on Android.

Since you're a customer, you should no longer use the Free repo here for iOS.  You should use the private repo for both iOS and Android now.

**Comment by christocracy** [comment]
P.S.  Sorry for late reply -- I was on Vacation the past 10 days.
