### ISSUE TITLE
Location getting delayed when I add License key to Android app

### ISSUE THREAD

**Issue by mohankyro22** [transistorsoft/react-native-background-geolocation#1976]
Location getting delayed when I add License key to Android app

- Significantly there is delay in getting the current location when I added the License key to the Android App. 

Before adding the License key it was about 2 or 3 seconds to get the currentLocation but after adding License key it is taking about 10 seconds. 

Is there any way I can overcome the above. 

@christocracy Would be happy to hear from you.

**Comment by christocracy** [comment]
You *must* provide the *Issue Template*.




## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by christocracy** [comment]
- Go [here](https://github.com/transistorsoft/react-native-background-geolocation/issues/new), copy all the text.
- Edit your original post and provide all the requested information.

**Comment by mohankyro22** [comment]
So closing this issue
