### ISSUE TITLE
iOS Location Permission Modal Pops Async to sdk start utility

### ISSUE THREAD

**Issue by GuptaAman08** [transistorsoft/react-native-background-geolocation#2122]
## Your Environment
* Plugin version: 4.13.1
* Platform: iOS
* OS version: iOS 17.4
* Device manufacturer / model:  iOS Phone
* React Native version (`react-native -v`): 0.71.18
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
{
      distanceFilter: 50,
      stopOnTerminate: true,
      startOnBoot: false,
      stopTimeout: 20,
      enableHeadless: false,
      heartbeatInterval: 60,
      locationAuthorizationRequest: 'WhenInUse',
      disableMotionActivityUpdates: false,
      extras: {},
      url: <server_url>,
      authorization: <function_that_returns_auth_token>,
      autoSync: true
}
```

## Expected Behavior
Actually, i have a doubt related to iOS behaviour of this sdk. 
When the code execution control arrives at line that has code - **await <your_sdk>.start()**, a location permission modal pops up. From here I see different behaviours in Android vs iOS
1. In case of Android, the control stops at that line unless some location permission is selected on that modal. Post that execution control will move to the next line
2. In case of iOS, the execution control doesn't stops at that line and wait for the user/customer to enter some location permission on that modal. Rather thats something async in case of iOS, because of which the execution moves ahead and completed my function in which your SDK's start utility was called.

## Actual Behavior
I am not sure, is that the right behaviour ??? 

## Steps to Reproduce

1. Start metro server and run an iOS build (react-native run-ios) 
2. Initialise the SDK by calling its ready method
3. Ensure the you have some console.log after the line **await <your_sdk>.start()** in the function (suppose **start_tracking**) from where you will start the location tracking
4. Call **start_tracking** and now observe that even though you dont select any permission on that location permission modal the function **start_tracking** will finish its execution. This is not the case in Android

**Comment by christocracy** [comment]
Is there a problem?

iOS and Android operate differently.

**Comment by GuptaAman08** [comment]
We were performing some action in the catch block. Since, in case of android we were getting error which is not the case in Iphone

**Comment by christocracy** [comment]
What error?

**Comment by GuptaAman08** [comment]
When you choose to Deny in case of Android, the sdk throws error, which is not the case in iOS

**Comment by christocracy** [comment]
You should handle permission issues in `.onProviderChange` event.

**Comment by christocracy** [comment]
Have you read the APIs docs .onProviderChange, as I mentioned above?  https://github.com/transistorsoft/react-native-background-geolocation/issues/2122#issuecomment-2310210177

**Comment by ItaGuy** [comment]
@christocracy thanks for the quick reply. Yes I did, however that event does not react to the user dismissing the dialog requesting "Always" (at least on ios). It does react to the user not giving "WhenInUse", but it's not really enough to cover all the user interactions. Users might click the wrong option by mistake (already happened even in internal testing) and not being able to react to that interaction is a hard limit for how the app can be aware of the user actions. As of now the only solution is start reacting when either they give or deny the "WhenInUse", but that still leads to errors in the location service and forces the app to act on a possibly incomplete state, because we have no way to know if the user will give or deny the "Always" permission (when they give it it's fine, but because there's no event for the dismiss we have no way to know if they have the dialog still open or closed it, forcing us to rely on "WhenInUse").

**Comment by christocracy** [comment]
If you more fine-grained permission management, I suggest you use a 3rd party plug-in specializing in permissions, such as react-native-permissions.

**Comment by ItaGuy** [comment]
will look into that, thanks. I get that this library will not consider implementing such functionalities right? Does this mean there's no way for a PR to add/extend the permissions management on ios to be considered and merged? With this I mean a PR either aligning the current Android and iOS behaviour, by making the await reliable to wait for the user response on the permissions dialogs OR extend one of the available events to react to the user dismissing the "Always" permission, so that the permission requests cycle is complete.

**Comment by ItaGuy** [comment]
hey @christocracy, just wanted to report that the method requestPermission seems to be indeed reliable to wait for the user interactions, even though it is advised against as permissions are requested by default from methods that need location. It honestly seems odd, I would expect .start to also wait for the permission request (if not completed yet, eg: first start) before returning. I guess my problem is solved like that, but maybe the plugin does have the needed functionalities to align Android and iOS? I suppose (from what I read) that Android does indeed start the plugin but waits for the permission request to be consumed first, while iOS does not (it's very clear when calling .start and .onLocation fires an error while the "WhenInUse" dialog is still open), even though it seems to be possible to do so before tracking.
Anyway thanks for your attention, I will be using .requestPermission for a more consistent experience for now, I hope it won't get deprecated.
