### ISSUE TITLE
How to test geolocation with Mockito

### ISSUE THREAD

**Issue by r0b0t3d** [transistorsoft/react-native-background-geolocation#254]
Hi @christocracy 
I would like to updates location base on mock location of Mockito app. How could I do that?

**Comment by christocracy** [comment]
Follow the directions for the mock app (usual developer options -> select Mock location app).

However, the plugin triggers the location-tracking state via accelerometer-based api.  The plugin doesn't care that mock locations are arriving because it's not listening to them.

Therefore, you must manually trigger into the "moving" state by:
- `changePace(true)` (the `stopTimeout` timer will eventually expire and the plugin will change back to "stationary" state and stop listening to locations.  I set a high `stopTimeout` when mocking, 15 minutes)
- Shake the device vigorously to simulate "walking"
