### ISSUE TITLE
Continually updating geofence

### ISSUE THREAD

**Issue by woodpav** [transistorsoft/react-native-background-geolocation#272]
I have a geofence created with identifier `unique_fence` and `geofenceschanged` is triggered when I initially create it.

After some time, I will recreate the `unique_fence` using `addGeofence` (same identifier and radius, different location) and the `geofenceschanged` object is not triggered.  

However, if I rebuild the app the `geofenceschanged` event is triggered.

It seems like the `geofenceschanged` event is only being triggered on app load and when the new identifier is not one of the old identifiers.

The current fix is to append the current time to the identifier (so !=) and then adding some logic to clean up unused fences. How do I fix this?

**Comment by christocracy** [comment]
This is probably a bug.  Should be easy to reproduce.

**Comment by christocracy** [comment]
In the future, please don't ignore the issue template:



## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
