### ISSUE TITLE
Advice: crash if user revokes permissions

### ISSUE THREAD

**Issue by aaronbuchanan** [transistorsoft/react-native-background-geolocation#346]
Just a question here, if a user goes to their settings and change their location preferences for our app, or disables their location for all apps, our app will crash. Subsequent starts will also crash. I'm assuming there's something I should be checking, but curious if there's any best practices here? 

LMK if anyone thinks this is a bug and I can be more descriptive, otherwise TIA!

**Comment by christocracy** [comment]
If you're seeing a *crash*, should you show me the log of that?

**Comment by christocracy** [comment]
And please:  **DO NOT IGNORE THE ISSUE TEMPLATE!**

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by 8-uh** [comment]
@aaronbuchanan if you're modifying the `locationAuthorizationAlert` configuration option, be aware that `react-native-background-geolocation` does not deep merge defaults. That is, if you modify -any- of the properties of the `locationAuthorizationAlert` object, you *must* set all options. Otherwise... you'll get crashes related to UIAlertController Actions... probably something (or exactly) like: `*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Actions added to UIAlertController must have a title'`

**Comment by christocracy** [comment]
This is why logs are important.

**Comment by omasback** [comment]
Seems like this should be in the docs

**Comment by aaronbuchanan** [comment]
Hey @christocracy  you can close this issue. I'd recommend pointing out that if one chooses to set `locationAuthorizationAlert`, they must set all fields (we were confused because the docs show default values, but those defaults are *only* set if you don't set `locationAuthorizationAlert` at all. I was expecting some kind of a merge, but it works if don't leave the button texts out)
