### ISSUE TITLE
Could not find com.google.android.gms:play-services-location:11.6.0

### ISSUE THREAD

**Issue by stroncod** [transistorsoft/react-native-background-geolocation#367]
## Your Environment
* Plugin version: 2.10.1
* Platform: Android
* OS version: 5.0.1
* Device manufacturer / model: Samsung
* React Native version (`react-native -v`): 0.49.3
* Plugin config

## Expected Behavior

App should compile

## Actual Behavior

Compiling error
## Steps to Reproduce

1. react-native run-android
2.
3.
4.

## Context
Trying to build the app, Google services won't load. I tried to re-install Google Repository with Android Studio, but same issue. Already try changing the build.gradle file, but nothing

## Debug logs

Scanning folders for symlinks in /Users/stroncod/Code/blindApp/blind/node_modules (12ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
File /Users/stroncod/.android/repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.google.android.gms:play-services-location:11.6.0.
     Searched in the following locations:
         file:/Users/stroncod/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.pom
         file:/Users/stroncod/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/stroncod/Code/blindApp/blind/android/sdk-manager/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/stroncod/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.pom
         file:/Users/stroncod/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/stroncod/Code/blindApp/blind/android/sdk-manager/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
     Required by:
         blind:app:unspecified > blind:react-native-background-geolocation:unspecified
   > Could not find :tslocationmanager:.
     Searched in the following locations:
         file:/Users/stroncod/Library/Android/sdk/extras/google/m2repository//tslocationmanager//tslocationmanager-.pom
         file:/Users/stroncod/Library/Android/sdk/extras/google/m2repository//tslocationmanager//tslocationmanager-.aar
         file:/Users/stroncod/Code/blindApp/blind/android/sdk-manager//tslocationmanager//tslocationmanager-.aar
         file:/Users/stroncod/Library/Android/sdk/extras/android/m2repository//tslocationmanager//tslocationmanager-.pom
         file:/Users/stroncod/Library/Android/sdk/extras/android/m2repository//tslocationmanager//tslocationmanager-.aar
         file:/Users/stroncod/Code/blindApp/blind/android/sdk-manager//tslocationmanager//tslocationmanager-.aar
     Required by:
         blind:app:unspecified > blind:react-native-background-geolocation:unspecified
   > Could not find com.google.android.gms:play-services-location:11.6.0.
     Searched in the following locations:
         file:/Users/stroncod/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.pom
         file:/Users/stroncod/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/stroncod/Code/blindApp/blind/android/sdk-manager/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/stroncod/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.pom
         file:/Users/stroncod/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
         file:/Users/stroncod/Code/blindApp/blind/android/sdk-manager/com/google/android/gms/play-services-location/11.6.0/play-services-location-11.6.0.jar
     Required by:
         blind:app:unspecified > blind:react-native-google-places:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.747 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by christocracy** [comment]
Google now hosts their own maven repo for play-services 11.2.0+.  See the bit in the setup docs directing you to add this maven repo:


https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md#gradle-configuration

**Comment by rayjadore** [comment]
i have the same issue to mine is version 11.8.0

**Comment by christocracy** [comment]
@rayjadore Did you add the [**required** Google `maven url`](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/INSTALL-ANDROID-RNPM.md#gradle-configuration)?

**Comment by Waffun** [comment]
I have the same issue

**Comment by HotelIT** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
        googlePlayServicesVersion = "16.1.0" // or set latest version
        androidMapsUtilsVersion = "0.5+"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
            
        }
        maven { url "https://jitpack.io" }
        maven { url "https://maven.google.com" }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
 and app/bild.gradle

apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.uf"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
        missingDimensionStrategy 'react-native-camera', 'general'
    }
    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile project(':react-native-camera')
    compile project(':react-native-maps')
    compile project(':react-native-vector-icons')
    compile project(':react-native-gesture-handler')
    compile ("com.google.android.gms:play-services-vision:16.1.0") {
      force = true;
   }
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

**Comment by christocracy** [comment]
@HotelIT See the [Android Setup Docs](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-ANDROID-RNPM.md#open_file_folder-androidbuildgradle).  `ext.googlePlayServicesLocationVersion`
