### ISSUE TITLE
locationUpdateInterval for iOS

### ISSUE THREAD

**Issue by normanrz** [transistorsoft/react-native-background-geolocation#45]
Is there no `locationUpdateInterval` in the iOS version?
For my use case it is completely sufficient to send the location data every 5-10s to the server. But iOS seems to be updating the location way more often. I know there is the distanceFilter, but I'd rather sample per time than per distance-change.

**Comment by christocracy** [comment]
Native location apis are not time-based -- they're distance-based.  You're always  bound by `distanceFilter`

Android's `locationUpdateInterval` merely controls how often a location is picked out of the location stream and sends to your app.  It's still bound by `distanceFilter`.

**Comment by normanrz** [comment]
I know, I am more concerned about the interval that the data is sent to the server.

**Comment by christocracy** [comment]
Ah, I see.  I think what you want is this [allowDeferredUpdatesUntilTimeTravelled](https://developer.apple.com/library/ios/documentation/CoreLocation/Reference/CLLocationManager_Class/#//apple_ref/occ/instm/CLLocationManager/allowDeferredLocationUpdatesUntilTraveled:timeout:)

I'm due to implement this.  This is the final party of the `CLLocationManager` api which I have not yet implmented (few people requested it.  I had someone on the Cordova side request this recently, so I'll go ahead and start implementing it soon)

**Comment by normanrz** [comment]
That sounds great! If I understand correctly that will limit the requests to a specified interval. but I would also be interested in always sending the current location every 5s (even if the location didnt change). like a heartbeat to the server. 
would that be possible with this api? or would i need a background task for that?

**Comment by christocracy** [comment]
What is the nature of your app that you require a location at `1/5 Hz` regardless of location-change?

**Comment by normanrz** [comment]
It is a realtime tracking app with fairly high precision. The frequency doesn't have to be `1/5 Hz`, but I want to be able to tell if the tracking is still active or disconnected / app crashed.

**Comment by christocracy** [comment]
And when the user is sitting in a movie theatre for 2 hours, for example, what are your expectations?

**Comment by normanrz** [comment]
In our app the user will explicitly start/stop live tracking (except when they lose network connectivity, app crashes, battery dies etc.)

**Comment by christocracy** [comment]
Regarding iOS specifically, this module has 4 possible states:
1.  **Stationary:**.  App is suspended.  No code is running.  No tracking.
2.  **Moving:**  App is awake and actively recording a location each `distanceFilter` meters.
3.  **Stop-detection:**.  Geolocation radios are off to conserve power.  Module is aggressively monitoring the accelerometer for movement.  If movement is detected (and the device has moved `distanceFilter` meters beyond last-location, **State #2** engages.  If `stopTimeout` expires before, the module switches to **State #1** or **State 4** (if `preventSuspend: true`).  During this state, the module is cleverly preventing iOS from suspending the app by requesting 3 min background job from iOS.  When a background job is nearly expired, the module briefly turns on location-updates, requests another 3 min background-job, then turns of location-updates again.
4. **Heartbeat:**  This is a specialized state enabled with `preventSuspend: true, heartbeatInterval: {Integer seconds}`.  This state hi-jacks iOS's natural desire to suspend an app when location-services are powered down, keeping the CPU spinning indefinitely by using requesting background-jobs as described in **State #3**.  During this state, the accelerometer is sampled at `1Hz`.  If *any* movement as all is detected after a `heartbeatInterval`, the location-radios will engage at full power and a very high-quality location is requested.  If the device is determined to be moving (ie: speed is reported or the device has moved beyond the `stationaryRadius`, **State #2** is engaged.  Otherwise, the module will simply return the current stationary-location.

- **State #4** is **very** new.  It was paid for and implemented for a single customer with specific requirements.

-

**Comment by normanrz** [comment]
I understand. Thanks for taking the time to explain!

**Comment by kholiavko-roman** [comment]
@christocracy, can you tell me please, on ios update by time is absent ? 
I want to set up update by distance and by time at one time, if its possible.

**Comment by christocracy** [comment]
iOS location API is strictly *distance-based* (ie: `distanceFilter`)

**Comment by kholiavko-roman** [comment]
Thank you!
