### ISSUE TITLE
[iOS] Is there anyway to guarantee a heartbeat every 4 minutes?

### ISSUE THREAD

**Issue by JAStanton** [transistorsoft/react-native-background-geolocation#46]
Regardless if the app is active or not. What would a configuration look like for that?

**Comment by christocracy** [comment]
There is now but be careful because it will have a drastic effect upon battery-life.

@see [preventSuspend](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/api.md#param-boolean-preventsuspend-false) and [heartbeatInterval](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/api.md#param-integer-heartbeatinterval-60)

```
  preventSuspend: true,
  heartbeatInterval: 60  // 60 seconds
```

while the plugin is in `preventSuspend` mode, location-services are **OFF** and the accelerometer is constantly monitored for movement.  When movement is detected, it will attempt to fetch a high-accuracy location to determine if the device has moved beyond the current-location.

Be aware that `preventSuspend: true` will keep the device's CPU spinning constantly 24 hours a day so you should have some mechanism in-place to turn OFF `preventSuspend` at some point (eg: only run it during business hours 9-5, for example).
