### ISSUE TITLE
Question: Lower location frequency by time instead of distance

### ISSUE THREAD

**Issue by Edwardillo** [transistorsoft/react-native-background-geolocation#515]
## Your Environment
* Plugin version: 2.12.2
* Platform: iOS

Is there any way to lower the location frequency by time instead of distance?

**Comment by christocracy** [comment]
*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
The most important information in the template is:

- Plugin version:
- Platform: iOS or Android
