### ISSUE TITLE
How to get current location provider state?

### ISSUE THREAD

**Issue by mattiamanzati** [transistorsoft/react-native-background-geolocation#525]
## Your Environment
* Plugin version: 2.12.2
* Platform: Both iOS and Android
* React Native version (`react-native -v`): 0.55.4

## Context

I want to provide a custom UI prompt to tell the user to enable both location services and GPS.
The `providerchange` event is perfect because it gives back all the information I need, like gps enabled, wifi enabled, location service enabled etc.... Unfortunatelly it's provided only as event, and its data is not returned by `getState` or similar.

I would love to get that data when my app router mounts the page or starts the app to either or somehow force a trigger of `providerchange` event.

**Comment by christocracy** [comment]
The `providerchange` event is *always* fired when your app boots.  Simply listen to the event *before* you execute `#ready` (the `#ready` method *causes* the `providerchange` event to fire at each boot.

**Comment by willmcclellan** [comment]
@christocracy I'm running into a similar problem with this behaviour and although it works as suggested, it's a little awkward to handle in development mode.

Because the `onProviderChange` event only fires on boot, it doesn't fire when reloading react-native. What I'm doing is checking `state.enabled` (via `getState`) and `provider.enabled` to determine whether to prompt the user to enable location services. But since provider state isn't available in `getState` I have to store it myself and when that isn't fired on reloads it breaks that logic. It's only development, but I could see the same behaviour on code push which we use in production.

Would it be possible to include the provider status in `getState`? Or being able to manually request provider status?

**Comment by willmcclellan** [comment]
This is probably better being tracked in #623

**Comment by christocracy** [comment]
See the CHANGELOG
