### ISSUE TITLE
Question regarding premium version (Android)

### ISSUE THREAD

**Issue by Luckygirlllll** [transistorsoft/react-native-background-geolocation#532]
Hello, we would like to start use premium version of your plugin for Android, that's why I have couple of questions: 
1) Is it show notifications in drawer to user, when app is in background, that app is doing geolocation tracking? If yes, is it possible to remove these notifications? 
2) Can we use this plugin for distance tracking? 
3) How fast it will drain the battery if the geolocation tracking will be both in background and foreground?

**Comment by christocracy** [comment]
>Is it show notifications in drawer to user, when app is in background, that app is doing geolocation tracking? If yes, is it possible to remove these notifications?

Android 8 made *big* changes to [Background Execution Limits](https://developer.android.com/about/versions/oreo/background).  In order for the plugin to run properly with Android 8+, it **must** run as a foreground-service, which **requires** a persistent notification.  However, foreground-services are the best mode to run this plugin anyway, since it almost guarantees the OS will not terminate the tracking service when under memory pressure from other apps.

>Can we use this plugin for distance tracking?

The plugin has an `odometer` reported with each location in addition to methods to `#getOdometer`, `#setOdometer`, `#resetOdometer`.

>How fast it will drain the battery if the geolocation tracking will be both in background and foreground?

That depends on many things, including device model, battery size / health.  The plugin does its best to conserve battery by only engaging location-services when the device is detected to be in-motion.  Also, one of the biggest drains on battery is HTTP requests -- you conserve a lot of battery by "throttling" http requests.  The plugin has several options to throttle its own http requests, including `#batchSync`, `#autoSyncThreshold`.

**Comment by christocracy** [comment]
And can you posting questions to the Mauron85 fork of my plugin.  Are you aware that’s a fork from nearly 4 years ago of my original open source project.

Mauron85 does not support geofences (not will it ever).  Mine does.

There’s a reason I charge to use mine:  full time support.

**Comment by Luckygirlllll** [comment]
@christocracy That's cool! Thanks for answers!

**Comment by Luckygirlllll** [comment]
@christocracy One more question, is it possible with this plugin to determine the activity? for example, does  user driving car,  or does user walking?

**Comment by christocracy** [comment]
Yes.  I suggest you see the docs for all available events, including `activitychange`
