### ISSUE TITLE
Override the HTTP template substantially

### ISSUE THREAD

**Issue by amirey** [transistorsoft/react-native-background-geolocation#553]
Hi Chris

I'm having issues coupling our APIs and the HTTP templating options. I need to get towards this template:

```{
    "location": [
        {
            "latitude":   [Float],
            "longitude":  [Float],
            "accuracy":   [Float],
            "speed":      [Float],
            "heading":    [Float],
            "altitude":   [Float]
            "timestamp": [ISO-8601 UTC] // eg:  "2015-05-05T04:31:54.123Z"
        },
        {
            "latitude":   [Float],
            "longitude":  [Float],
            "accuracy":   [Float],
            "speed":      [Float],
            "heading":    [Float],
            "altitude":   [Float]
            "timestamp": [ISO-8601 UTC] // eg:  "2015-05-05T04:31:54.123Z"
        }
    ],
    "extras": {   // <-- optional extras.  @see #getCurrentPosition for details
        "foo": "bar"
    }
}
```

That:
1. removes completely the "coords" key that precedes location objects
2. puts the timestamp into the location object

Is there an area in this repo that controls this logic and that I can override, or is it native code that is outside of the scope of the library?

Thanks

**Comment by christocracy** [comment]
Please **do NOT ignore** the issue template:

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
See [HTTP Features](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/docs/http.md).  This guide is linked from the documentation in several places.

You might also glance at the available [HTTP & Persistence Options](https://github.com/transistorsoft/react-native-background-geolocation/tree/master/docs#wrench-http--persistence-options) in the docs, where you'll find some options that look particularly interesting, such as **`locationTemplate`**
