### ISSUE TITLE
Unable to fetch location after closed the App in Android

### ISSUE THREAD

**Issue by bajrangsharma-burrp** [transistorsoft/react-native-background-geolocation#561]
Unable to fetch location after kill the App in Android...How can we fetch?...

How can we fetch continuous location even if App is closed...

How can we run a service on OS level not an App level to fetch the location after closed the App by swipe?...

configuration as below:

stopOnTerminate: false,
startOnBoot: true,
locationUpdateInterval: 2 * 1000,
fastestLocationUpdateInterval: 2 * 1000,
forceReloadOnLocationChange: false,
forceReloadOnMotionChange: false,
forceReloadOnGeofence: false,

**Comment by bajrangsharma-burrp** [comment]
configuration as below:
      stopOnTerminate: false,
      startOnBoot: true,
      locationUpdateInterval: 2 * 1000,
      fastestLocationUpdateInterval: 2 * 1000,
      forceReloadOnLocationChange: false,
      forceReloadOnMotionChange: false,
      forceReloadOnGeofence: false,

**Comment by christocracy** [comment]
**DO NOT IGNORE THE ISSUE TEMPLATE**

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

**Comment by christocracy** [comment]
closed for lack of feedback.
