### ISSUE TITLE
Wrong timestamp

### ISSUE THREAD

**Issue by francelaquino** [transistorsoft/react-native-background-geolocation#563]
I'm using the free trial

I'm getting different timestamp compare with my Android phone's time.
with the below code my timestamp is 
timestamp: '2018-09-16T07:34:46.369Z', <- 7:34:46 AM
my Android  phone time : 10:34:46AM

BackgroundGeolocation.ready({
            debug: false,
            logLevel: BackgroundGeolocation.LOG_LEVEL_OFF,
            allowIdenticalLocations :true,
            stationaryRadius:5,
            maxDaysToPersist: 1,
            foregroundService: true,
            stopOnTerminate: false, 
            startOnBoot: true, 
            url: '',
            method: 'POST',
            batchSync: false,       
            autoSync: true,       
          
        }).then(state => {
            if (!state.enabled) {
                BackgroundGeolocation.start(function () {
                });

             
            }
        }).catch(error => {
        });

 componentDidmount() {
    BackgroundGeolocation.getCurrentPosition((location) => {
             console.log(location)
   }, (error) => {
    }, { samples: 1, persist: true,desiredAccuracy: 10,timeout: 30,maximumAge: 5000 });
}

Thanks

**Comment by christocracy** [comment]
There is an issue template which you've ignored.  Did you notice the **WARNING** at the top?

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs
