### ISSUE TITLE
How to remove persistent notification "Location Service Activated" on Android?

### ISSUE THREAD

**Issue by cmcaboy** [transistorsoft/react-native-background-geolocation#605]
On android, there appears to be a persistent notification that users can see labeled 'Location Service activated'. Is it possible to remove this notification, but still track location in the background?

![image](https://user-images.githubusercontent.com/1489169/47968179-38c29e80-e034-11e8-8689-a1fa6d403883.png)

## Your Environment
* Plugin version: 2.12.2
* Platform: Android
* OS version: 9
* Device manufacturer / model: Google Pixel
* React Native version (`react-native -v`): 0.57
* Plugin config

BackgroundGeolocation.on('location', this.onLocation, this.onError);

    BackgroundGeolocation.ready({
      reset: false,
      desiredAccuracy: 100,
      distanceFilter: 100,
      stopTimeout: 5,
      debug: false, 
      logLevel: BackgroundGeolocation.LOG_LEVEL_NONE,
      stopOnTerminate: false,   
      startOnBoot: true,       
      url: GEO_LOCATION_URL,
      batchSync: false,       
      autoSync: true,   
      extras: {
        id,
      },
      params: { 
        id,
      },
    }, (state) => {
      if (!state.enabled) {
        BackgroundGeolocation.start(() => {
          console.log(' - Start success');
        });
      }
    });

## Expected Behavior

The app should track geolocation in the background/closed without the persistent notification

## Actual Behavior

The app tracks geolocation in the background, but the 'Location Service Activated' notification persists.

## Steps to Reproduce

1. Setup react-native-background-geolocation on android.
2. Set stopOnTerminate to false
3. Start app, accept permissions, place app in background or close.
4. See persistent notification

## Context

I don't want my users to be bothered by a persistent notification when tracking their location.

## Debug logs
Can provide on request.

**Comment by christocracy** [comment]
With Android 7’s new Background Execution Limits, the notification is required.  It cannot be hidden.  You may modify the text and icon.

Watch this video:
https://m.youtube.com/watch?v=Pumf_4yjTMc

**Comment by cmcaboy** [comment]
Makes sense. Thank you for the info.

**Comment by Udbhav12** [comment]
@christocracy - I am seeing this 'Location Service Activated' notification in those devices also which do not have Android 8.

eg - Lenovo A6 (Android 5.1.1)

**Comment by christocracy** [comment]
@Udbhav12 See docs for [`foregroundService`](https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#foregroundservice)

**Comment by aksonov** [comment]
@christocracy We tested few background-geolocation apps and they don't have such notification (except Life360), Android 8.0.0, Samsung S7, why?

![54835734-bbb95e00-4c90-11e9-8cae-10885afe6b6a](https://user-images.githubusercontent.com/1321329/54838323-a102db80-4cc8-11e9-807a-9cc2cf577a7a.png)

**Comment by christocracy** [comment]
This is what version `3.0.0` is all about.  The foreground-service will be shown only when the plugin is in the *moving* state, just like Life 360 (which I have installed).

**Comment by christocracy** [comment]
Version `3.0.0` will also introduce `useSignificantChangeOnly: true` for Android now, as well.

This gives you no Android foreground service *at all*.  You will receive only "a few locations per hour".

If you want aggressive tracking according to your configured `distanceFilter`, you *must* accept a foreground-service (this is what Life 360 does when you're in in a vehicle).

**Comment by alandmonte** [comment]
How to navigate to a specific screen after tapping on this notification? As of now, my app restarts even if its in the foreground on any particular screen

**Comment by natezander** [comment]
Hello and thank you for this awesome software.

On Android 8+, we recognize that the foreground-service must be turned on. However, the USER can turn this persistent notification off via the App's Settings AFTER app is installed.

Since Android 10 allows the user to adjust this setting, Is it recently possible to have this defaulted to off from the developer side? Thanks!

![Screenshot (Mar 10, 2020 10_28_10 AM)](https://user-images.githubusercontent.com/5290498/76335332-fa895f00-62b9-11ea-83b3-5d030a53ae08.png)

**Comment by christocracy** [comment]
No, this is not possible to default off

**Comment by Sulorb** [comment]
> Since Android 10 allows the user to adjust this setting, Is it recently possible to have this defaulted to off from the developer side? Thanks!

I don't have the perfect solution for now but still something that could help the user.
With the [Open Native Settings](https://ionicframework.com/docs/native/open-native-settings) you can this.openNative.open('application_details'); in order to open the settings of the app directly from a button of your app. The hard part is to explain the user has to deactivate the notifications from the background geolocation.

By the way, these notifications are sorted in a category which has the same name as the app, is it possible to change the name christocracy ? Something like "DEACTIVE ME TO HIDE THE NOTIFICATION" instead could be easier for the users.

My other hint to solve the problem would be to use [App Preferences](https://ionicframework.com/docs/native/app-preferences) but I didn't succeed to use it because it just crashed my build and I don't get anything of the [documentation](https://github.com/apla/me.apla.cordova.app-preferences) nor if it's supposed to change the App Preferences.

**Comment by christocracy** [comment]
Maybe the user doesn’t want you secretly spying on their location and appreciates knowing exactly when you’re tracking them.

**Comment by Sulorb** [comment]
You're right, after looking everywhere I accept to keep the notification on my app. Even more if I use this permanent notification to do an action with a [custom button](https://transistorsoft.github.io/cordova-background-geolocation-lt/interfaces/_cordova_background_geolocation_lt_.notification.html) added on it.
