### ISSUE TITLE
App is consuming power in the background

### ISSUE THREAD

**Issue by francelaquino** [transistorsoft/react-native-background-geolocation#611]
## Your Environment
* Plugin version: ^2.13.3
* Platform: Android
* OS version: Android 8.0
* Device manufacturer / model: Huawei Y7 Prime 8 / LDN-L21
* Device manufacturer / model: Huawei Nova 3e / ANE-LX1
* Device manufacturer / model: Huawei / ALE-L21
* React Native version (`react-native -v`):  ^0.55.4
* Plugin config
BackgroundGeolocation.ready({

             locationAuthorizationAlert: {
                 titleWhenNotEnabled: "Location services not enabled",
                 titleWhenOff: "Location services is off",
                 instructions: "You must enable in location services",
                 cancelButton: "Cancel",
                 settingsButton: "Settings"
             },
             reset:true,
             locationAuthorizationRequest: "Always",
             notificationPriority: BackgroundGeolocation.NOTIFICATION_PRIORITY_MIN,
             stopTimeout: 10,
             /*logLevel: BackgroundGeolocation.LOG_LEVEL_VERBOSE,
             debug: true,*/
             desiredAccuracy: BackgroundGeolocation.DESIRED_ACCURACY_HIGH,
             distanceFilter: 5,
             minimumActivityRecognitionConfidence:90,
             allowIdenticalLocations: false,
             triggerActivities: 'on_foot, walking, running, in_vehicle, on_bicycle',
             maxDaysToPersist: 3,
             persist: true,
             heartbeatInterval: 60,
             notificationTitle: '',
             notificationText: '',
             notificationChannelName: '',
             stopOnTerminate: false,
             startOnBoot: true,
             foregroundService: true,
             activityRecognitionInterval:100,
             forceReloadOnBoot: true,
             preventSuspend: true,
             fastestLocationUpdateInterval:30000 ,
             url: '',
             method: 'POST',
             batchSync: false,
             autoSync: true,
             params: {
                 "useruid": userdetails.userid,
                 "fcmtoken": userdetails.fcmtoken,
                 "model": Model,
                 "timezone": timeZone,
                 "manufacturer": Manufacturer
             }
            }, () => {
                BackgroundGeolocation.start();
            });

## Expected Behavior
The app should run continuously in foreground or background

## Actual Behavior
The mobile is stopping the app even though there is enough battery. 
It also show a message app is frequently positioning

## Context
I also download the sample application from play store and let it run, its show a message BG Geolocation is consuming power in the background, then after a while the app stops working. 

So far all this happens using Huawei

**Comment by christocracy** [comment]
Chinese device manufacturers, such as Huawei are horrible when it comes to foreground-services.   Their flavour of Android is far too aggressive killing foreground-services.  Yes, the plugin's foreground-service is subscribed to the MotionActivity API (which consumes *little* power) in order to determine when the device is moving so it can know when to run on location-services and begin tracking (and importantly so it can know when the device is *no longer* moving, so it can turn *off* location-services).

Try this:  
- Start a music player (eg: Play Music).  
- Begin playing a song. 
- Terminate the music player.

The music should continue playing.

**Comment by francelaquino** [comment]
Yes, the music still playing. May I know your point? (sorry)

Is my config needs adjustment to fix the issue?

**Comment by christocracy** [comment]
>Yes, the music still playing. May I know your point? (sorry)

Because the plugin runs a foreground-service *just as a music player does*.  Some Chinese devices actually *stop* playing music when the player app is terminated, *OnePlus*, I think.

Keep your music player playing and see if the OS eventually terminates it.

Quite often, the solution to prevent the plugin's tracking service stopping is the same for people searching for ["Why is my music player stopping?"](https://www.google.ca/search?q=huawei+music+player+stops+playing&rlz=1C5CHFA_enCA816CA816&oq=huawei+music+player+stops+playing&aqs=chrome..69i57.7199j0j4&sourceid=chrome&ie=UTF-8)

**Comment by francelaquino** [comment]
Our app is working fine, except huawei, do you have idea or workaround that we can do to solve the issue.

**Comment by christocracy** [comment]
I have a Huawei P20 arriving today.
