### ISSUE TITLE
Debugging config

### ISSUE THREAD

**Issue by jeroenbourgois** [transistorsoft/react-native-background-geolocation#62]
Hi

I have spent the last two days trying every possible configuration and setup, installing the `0.4.1` and the `0.4.3` but I always endup with `- [js] BackgroundGeolocation started successfully` (a log I took from the demo app)

I have no idea where to start looking why it is not working. I got it working last week and don't know what I changed.

Do you have some steps to check what is causing the configure to fail? Or more in detail: why is the `state.enable` in the configure callback `false`? When I inspect the `state` object itself I cannot find errors or such.

We also bought the android version which is working in the emulator but not on an actual device. But I would lik to get it working on iOS first before moving on.

Thank you for your input!

**Comment by jeroenbourgois** [comment]
Hmmm strangest thing: when I call the `BackgroundGeolocation.start()` even with `state.enabled === false` it then seems to work and sending out data to my `requestb.in`! Is this the correct behaviour? It works now but then I wasted a lot of time because I misunderstood :)

**Comment by christocracy** [comment]
Sorry for the delay, I'll have a look.

**Comment by christocracy** [comment]
I can't confirm this but I've pushed a new version `0.4.4`.  Also, i've reverted the installation procedure back to my original idea.  I had tried copying `react-native-mapbox-gl`'s idea of adding the `TSLocationManager.framework` to **Embedded Binaries** but that turned out to be *far* more trouble (particularly when archiving to submit to Apple, but also when updating the plugin to a new version).  You may want to try completely uninstalling the plugin (browse your application folder and make sure there no orphaned copy of `TSLocationManager.framework`).

**Comment by jeroenbourgois** [comment]
Ok, thanks for the update. For now I will keep on just starting the geolocation regardless of the callback. This can be closed for me, I will test 0.4.4 later in the project
