### ISSUE TITLE
Android Devices Displaying "Location Service Activated"

### ISSUE THREAD

**Issue by adamhaney** [transistorsoft/react-native-background-geolocation#694]
## Your Environment
* Plugin version: 3.0.0
* Platform: Android
* OS version: Multiple? 

* Device manufacturer / model: Impacting multiple Android Devices.
* React Native version (`react-native -v`): 0.59.4
* Plugin config

## Expected Behavior
User is not notified every time location services are used.

## Actual Behavior
Several of my users have reported being shown this issue as of the latest update of my app.

### User 1 Screenshot
![image1 (2)](https://user-images.githubusercontent.com/1839452/56502341-fdcbfe80-64df-11e9-9b9b-9c08af3c44b7.png)

### User 2 Screenshot
![Image from iOS (1)](https://user-images.githubusercontent.com/1839452/56502617-fb1dd900-64e0-11e9-80ab-f5ee5d0fd1cf.png)

## Steps to Reproduce
1. Install the latest version of our application
2. After several minutes of the application being in the background this message is shown to Android users.

## Context
I've been successfully using the react-native-background-geolocation service for over a year now (great software, thank you). As of the latest update I've had several of my Android users/testers complain that they're seeing 'Location Service Activated' message. I'm not definitely sure exactly what's going on here. It's possible I've misconfigured something, or that this is expected behavior. I'm not an Android expert, nor am I an expert on the internals of the library so any guidance on possible causes or directions I could go with my investigation would be appreciated.

## Debug logs
I don't believe this is applicable, but if not having this is a blocker to a response please let me know what information would be helpful and I'll provide it.

**Comment by christocracy** [comment]
It's normal to see the foreground-service notification when the device is *moving*.  Also when the plugin is uploading records to your server (if you've configured an `#url`).

**Comment by bingle87** [comment]
How do I change the icon shown? It appears to be using the ic_launcher, not the ic_stat that i have all other notifications using?

**Comment by christocracy** [comment]
Search Config docs for the word “notification”

**Comment by littlehome-eugene** [comment]
How do we turn this off? 

1. set `url` empty string ?
2. is there a way to stop notification when device is moving while app is in background?  (since you said `foreground-service notification`)

**Comment by christocracy** [comment]
If receiving a location only every 500-1000 meters is sufficient for you, see docs Config.useSignificantChangesOnly.

Otherwise, the notification is **required**.  The only way to keep location-services on in background terminated states is via a “foreground service”.  Foreground services **require** a persistent notification.  There is absolutely, 100% no way around this.

You don’t get to aggressively and secretly track a device without the user’s knowledge.

**Comment by littlehome-eugene** [comment]
Are you implying we can avoid the notification `completely` if we use the `Config.useSignificantChangesOnly` option?

**Comment by christocracy** [comment]
What do the docs say?

**Comment by littlehome-eugene** [comment]
> If receiving a location only every 500-1000 meters is sufficient for you, see docs Config.useSignificantChangesOnly.
> 
> Otherwise, the notification is required. 

Your wording sounded so, which doc are you refering?

**Comment by christocracy** [comment]
The *API Docs*, what else?

**Comment by littlehome-eugene** [comment]
So here's my foundings, I understand you get to answer same question over and over, 
but its kinda hard to collect information and figure out what are our best options.. :(


I have marked `(Q)` before questions, can you take a look please



how to minimize notification if you only need course location

* android

** useSignificantChangesOnly

android notification will be (location service activated) turned off

** url
notification is triggered when app uploads via url
(Q) Is useSignificantChangesOnly=true effectively turn this off?
(Q) how do we turn this option off independently (setting url=''?)

* ios
** useSignificantChangesOnly

# https://github.com/transistorsoft/react-native-background-geolocation/issues/288#issuecomment-314953143
useSignificantChangesOnly: true doesn't work with doesn't work with locationAuthorizationRequest = WhenInUse. It only works when user has selected Always in Privacy -> Location

** useSignificantChangesOnly=true

- with locationAuthorizationRequest=any


  if user selects "WhenInUse",
  useSignificantChangesOnly is ignored, and app will use aggresive tracking when app is running (Does "WhenInUse" mean forground running or app running either in foreground/background)
  if user selects "Always",
  useSignificantChangesOnly is true, and app will use non-aggresive tracking

- with locationAuthorizationRequest=always

  if user selects "WhenInUse", user gets alert from geo-library + ios-notification


** Assuming user selecting "WhenInUse", our best bet is requesting location service less frequently
Following options may have an affect

- url
- distanceFilter
- (Q) are there other siginificatn options?



* useSignificantChangesOnly
# https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#usesignificantchangesonly

location will be recorded only periodically (approx 500 m - 1000m)
distanceFilter, stationaryRadius, activityType, etc. will have no effect


* locationAuthorizationRequest
# https://transistorsoft.github.io/react-native-background-geolocation/interfaces/_react_native_background_geolocation_.config.html#locationauthorizationrequest
If you configure Any, the plugin allow the user to choose either Always or WhenInUse

WhenInUse disables geofence
(Q) is there a way of presenting user an option of "always" or "never", since if we lose geofence, we get almost no functionality
