### ISSUE TITLE
Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by anshumanburman** [transistorsoft/react-native-background-geolocation#777]
i have integrated this library successfully but when i run the code it gives such error "Cannot read property 'addEventListener' of undefined".

**Comment by christocracy** [comment]
You have ignored the required issue template:

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
