### ISSUE TITLE
Cannot able to install 

### ISSUE THREAD

**Issue by kumaresan-cgvak** [transistorsoft/react-native-background-geolocation#890]
Whenever i try to install the plugin using the commant 'npm install react-native-background-geolocation --save' I'm getting an error 
'npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2019-11-01T10_13_24_440Z-debug.log'

**Comment by christocracy** [comment]
*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>

**Comment by kumaresan-cgvak** [comment]
Plugin version: 3.3.2
Platform: iOS and Android
OS version: MAC OS Version 10.13.6
Device manufacturer / model: 
React Native version (react-native -v): "0.61.3"
Plugin config
