### ISSUE TITLE
setConfig() callback

### ISSUE THREAD

**Issue by neno-giscloud** [transistorsoft/react-native-background-geolocation#91]
The documentation is inconsistent on whether or not setConfig() accepts a callback. Probably c/p from the configure() method.

![image](https://cloud.githubusercontent.com/assets/948756/15990582/c324ee52-3096-11e6-94dd-3895890e9c42.png)

EDIT: just saw a pull request which addresses the issue #88 

While we're at it, does it need a callback? Is the new configuration applied synchronously somehow even while the plugin is tracking device location?

**Comment by christocracy** [comment]
This is a bit confusing.  iOS [doesn't accept a callback](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/RNBackgroundGeolocation/RNBackgroundGeolocation.m#L62) but Android does.

iOS applies the config immediately but Android posts it asynchronously to `EventBus` for the background-service to receive and process.

However, both will apply the config live (eg: if you're already tracking with a `distanceFilter: 10` then change it to `50`, the change will apply immediately.  I think I'll simply remove the callback from both, since it's not necessary.
