### ISSUE TITLE
when app terminated ,  i set stopOnTerminate: false. I want to take the position for a certain period of time

### ISSUE THREAD

**Issue by ducanh13121997** [transistorsoft/react-native-background-geolocation#946]
when app terminated ,  i set stopOnTerminate: false. how to get location on 15 minutes ?????  help me , please

**Comment by christocracy** [comment]
I don’t exactly know what you mean, it’s unclear.
- you want to track for exactly 15min after terminate them stop?
- or you want a location *every* 15min?

**Comment by ducanh13121997** [comment]
i want a location every 15min

**Comment by christocracy** [comment]
The plugin imports react-native-background-fetch as a dependency (also made by transistorsoft).  You’ll want to implement that and execute #getCurrentPosition in its callback.

**Comment by ducanh13121997** [comment]
help me !!!!
i want location when app terminated ,  every 300m ????

**Comment by christocracy** [comment]
You have ignored the issue template.   You were asked to provide this information:

*****************************************************************
* WARNING:  If you ignore this template, so too will your issue
*****************************************************************


## Your Environment
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* React Native version (`react-native -v`):
* Plugin config
```javascript <!-- Syntax-highlighting:  paste your code below -->
PASTE_YOUR_CODE_HERE
```

## Expected Behavior


## Actual Behavior


## Steps to Reproduce

1.
2.
3.
4.

## Context


## Debug logs

<details><summary>Logs</summary>

``` <!-- Syntax highlighting:  DO NOT REMOVE -->
PASTE_YOUR_LOGS_HERE
```

</details>
